# config_version=4
# NBX (The Nightmare Before Christmas Pinball)

mode:
  start_events: ball_starting
  priority: 8500

ball_saves:
  default:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_Ball_Save_started
    timer_start_events: balldevice_bd_plunger_ball_eject_success
    auto_launch: true
    balls_to_save: 1
    debug: true

  multiball:
    active_time: 15s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: enable_the_mb_ball_save
    #timer_start_events: enable_the_mb_ball_save
    auto_launch: true
    balls_to_save: -1
    debug: true

  unlimitied:
    active_time: 30s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: start_ball_save_30s
    auto_launch: true
    balls_to_save: -1
    debug: true




sound_player:
  ball_saved1: Dont_Give_Up
  ball_saved2: im_sorry
  ball_saved3: sorry_ill_be_good

  
random_event_player:
  ball_save_default_saving_ball:
  - ball_saved1
  - ball_saved2
  - ball_saved3
 

widget_player:
  ball_save_default_saving_ball: 
    widget_ballsave:
      widget_settings:    
        expire: 2.5s
      slide: leftframe        
    

widgets:
  widget_ballsave:
  - type: text
    style: tall_title
    font_size: 30
    color: 5476cb
    text: BALL SAVED
    y: 40
    z: -1301
  - type: image
    image: angel_jack
    anchor_y: top
    anchor_x: left
    y: top
    x: 0        
    z: -1300        
        
        

show_player:
  ball_save_default_enabled:
   red_flash:
      key: rball_save_flash
      show_tokens:
        leds: rgb_keepshooting
      speed: 4
      loops: -1
      
  ball_save_default_disabled:
    rball_save_flash:
      action: stop
      
  ball_save_multiball_enabled:
    blue_flash:
      key: mball_save_flash
      show_tokens:
        leds: rgb_keepshooting
      speed: 4
      loops: -1
      
  ball_save_multiball_disabled:
    mball_save_flash:
      action: stop


  ball_save_unlimited_enabled:
    green_flash:
      key: uball_save_flash
      show_tokens:
        leds: rgb_keepshooting
      speed: 4
      loops: -1
      
  ball_save_unlimited_disabled:
    uball_save_flash:
      action: stop

