#config_version=4

high_score:
  shift_left_tag: left_flipper
  shift_right_tag: right_flipper
  select_tag: start
  categories:
  - score:
    - GRAND CHAMPION
    - HIGH SCORE 1
    - HIGH SCORE 2
    - HIGH SCORE 3
    - HIGH SCORE 4
  - loops:
    - MOST LOOPS

slide_player:
  high_score: slide_hs
  high_score_award_display: slide_hsa
  
  
slides:
  slide_hs:
  - type: text
    text: PLAYER (player_num)
    style: medium
    anchor_y: bottom
    x: center-27
    y: bottom+21
  - type: text
    text: (award)
    style: small
    anchor_y: bottom
    x: center-27
    y: bottom+12
  - type: text_input
    key: high_score
    style: medium
    anchor_y: bottom
    max_chars: 3
    y: bottom
  - type: text
    text: A
    key: high_score
    anchor_y: bottom
    anchor_x: left
    x: left+90
    y: bottom+12
    style: medium
    animations:
      entrance:
      - property: opacity
        value: 1
        duration: 0.5s
      - property: opacity
        value: 0
        duration: 0.5s
        repeat: true
  slide_hsa:
  - type: text
    text: (player_name)
    color: 0
    y: middle-2
    animations:
      entrance:
      - property: opacity
        value: 1
        duration: 0.05s
      - property: opacity
        value: 0
        duration: 0.05s
        repeat: true
  - type: text
    text: (award)
    style: medium
    anchor_y: top
    y: top-2
