#config_version=4
show_player:
  mode_attract_started:
    attract_dmd_loop:
      action: play
      loops: -1
      speed: 1
    gi_fade:
      loops: -1
      speed: 1
    arrow_sweep:
      loops: -1
      speed: 8
    holiday_sweep:
      loops: -1
      speed: 8
    jack_santa_sweep:
      loops: -1
      speed: 6
    oogie_sweep:
      loops: -1
      speed: 4
    misc_sweep:
      loops: -1
      speed: 8
    lsb_sweep:
      loops: -1
      speed: 6         

  mode_attract_stopping:
    attract_dmd_loop:
      action: stop
    gi_fade:
      action: stop
    holiday_sweep:
      action: stop
    arrow_sweep:
      action: stop
    jack_santa_sweep:
      action: stop
    oogie_sweep:
      action: stop
    misc_sweep:
      action: stop
    lsb_sweep:
      action: stop
