#config_version=4
mode:
  start_events: ball_starting
  priority: 100
  code: Base.Base
  

  
scoring:
# 109,440 frames in the movie!!
#    left_orbit_unlit_hit:
#        Score: 1000
#    left_ramp_unlit_hit:
#        Score: 1500
  inner_left_loop_unlit_hit:
    score: 2000
  oogie_cw_loop_unlit_hit:
    score: 3330
  oogie_ccw_loop_unlit_hit:
    score: 6660
#    inner_right_loop_unlit_hit:
#        Score: 3500
#    right_ramp_left_unlit_hit:
#        Score: 4000
#    right_ramp_right_unlit_hit:
#        Score: 4250
#    right_orbit_unlit_hit:
#        Score: 4500
#    tub_lock_unlit_hit:
#        Score: 5000
  sw_slingl:
    score: 170
  sw_slingr:
    score: 170
  sw_doctor:
    score: 7500
#    balldevice_mayorscoop_enter:
#        Score: 5500
#    balldevice_soupvuk_ball_enter:
#        Score: 6000
#    sw_inthehole:
#        Score: 10000
#

sound_player:
  mode_base_started:
    loop_somethings_up:
      action: play
      loops: -1
      volume: 0.75
  
  mode_base_stopping:
    loop_somethings_up:
      action: stop  

  mode_base_stop_music:
    loop_somethings_up:
      action: stop  
      
  oogie_loop_cw_singlestep_unlit_hit: oogieloop
  oogie_loop_ccw_singlestep_unlit_hit: oogieloop_reverse

  
  balldevice_bd_plunger_ball_eject_attempt: ramp 1
  balldevice_bd_plunger_ball_eject_failed: sigh
  sw_subwaysneak: Tunnel
  sw_rrampgate: ramp 1
  sw_lrampgate: ramp 2
  mayor_spin_1: head_spin1
  mayor_spin_2: head_spin2
  mayor_hum1: mayor_hum1  
  mayor_hum2: mayor_hum2  
  mayor_hum3: mayor_hum3  
  mayor_hum4: mayor_hum4  
  say_a_reward: a_reward
  sw_subwaytree: Woah2
  soup_gate_open: du_du_da_da
  soup_gate_close: du_du_da_da
  sw_sling: sling_bounce
  doc_chair_1: Wheelchair_Noise
  doc_chair_2: Wheelchair_Noise2
  doc_chair_3: Wheelchair_Noise3
  doc_chair_4: Wheelchair_Noise4
  player_added_1_v2: I_have_every_confidence_in_you
  player_added_1_v1: shall_we_then
  player_added_2: here_let_me_show_you
  player_added_3: doctor_thank_you_for_coming
  player_added_4: bunny
  bark_bark1: bark_bark
  bark_bark2: bark_bark2
  bark_bark3: bark_bark3
  bark_bark4: bark_bark4
  zero_not_now: No_Zero_Down_Boy

  zero_mode_time_extended: allright
  zero_mode_time_extended_max: allright
  char_sally_qualified: sally2
  

random_event_player:
  sw_doctor:
  - doc_chair_1
  - doc_chair_2
  - doc_chair_3
  - doc_chair_4
  
  sw_zero: 
  - bark_bark
  
  char_mayor_qualified:
  - mayor_hum1
  - mayor_hum2
  - mayor_hum3
  - mayor_hum4

  char_zero_qualified:
  - bark_bark1
  - bark_bark2
  - bark_bark3
  - bark_bark4 
  
  player_added_1:
  - player_added_1_v2
  - player_added_1_v1





widget_player:
  player_added_2:
    player_2_score:
      slide: infoframe
    player_2_slot:
      slide: infoframe
  player_added_3:      
    player_3_score:
      slide: infoframe          
    player_3_slot:
      slide: infoframe          
  player_added_4:      
    player_4_score:
      slide: infoframe          
    player_4_slot:
      slide: infoframe  

  mode_base_started:
    w_backdrop1:
      slide: backdropframe  
  

      
widgets:
  w_backdrop1:
      - type: image
        image: backdrop1
        z: 50

  player_number:
      - type: text
        style: small
        text: PLAYER (player|number)
        anchor_y: top
        anchor_x: left        
        y: 9
        x: 2
        z: -2450
        color: 339966        
  ball_number:
      - type: text
        style: small
        text: BALL (ball)        
        anchor_y: top
        anchor_x: left        
        y: 9
        x: 50
        z: -2450
        color: 339966        
  credits_remaining:
      - type: text
        style: small
        text: (machine|credits_string)
        anchor_y: top
        anchor_x: left        
        y: 9
        x: 30
        z: -2450
        color: 333333        

  current_player_score:        
      - type: text
        style: mdm
        text: (score)
        min_digits: 2        
        number_grouping: true        
        anchor_x: left
        anchor_y: top        
        x: 2
        y: 30
        z: -2450
        color: 40ff40        
        
  player_2_slot:
      - type: text
        style: tinyscore2
        text: (machine|player_slot_2)
        anchor_x: left
        anchor_y: top        
        x: 130
        y: 27
        z: -2450
        color: 339966        
  player_2_score:                
      - type: text
        style: tinyscore2
        text: (machine|score_slot_2)
        min_digits: 2        
        number_grouping: true        
        anchor_x: left
        anchor_y: top        
        x: 139
        y: 27
        z: -2450
        color: 408f00        
 
  player_3_slot:
      - type: text
        style: tinyscore2
        text: (machine|player_slot_3)
        anchor_x: left
        anchor_y: top        
        x: 130
        y: 18
        z: -2450
        color: 339966        
  player_3_score:                
      - type: text
        style: tinyscore2
        text: (machine|score_slot_3)
        min_digits: 2        
        number_grouping: true        
        anchor_x: left
        anchor_y: top        
        x: 139
        y: 18
        z: -2450
        color: 408f00        

  player_4_slot:        
      - type: text
        style: tinyscore2
        text: (machine|player_slot_4)
        anchor_x: left
        anchor_y: top        
        x: 130
        y: 9
        z: -2450
        color: 339966        
  player_4_score:        
      - type: text
        style: tinyscore2
        text: (machine|score_slot_4)
        min_digits: 2        
        number_grouping: true        
        anchor_x: left
        anchor_y: top        
        x: 139
        y: 9
        z: -2450
        color: 408f00        

