# config_version=4
# NBX (The Nightmare Before Christmas Pinball)

#Door_Thanksgiving 

mode:
  start_events: door_mode_6_start
  stop_events: door_mode_6_stop
  code: Door_Thanksgiving.Door_Thanksgiving
  priority: 950


sound_player:
  holiday_thanksgiving_music_start:
    loop_Sabres1:
      action: play
      loops: -1
      volume: 0.5 

  holiday_thanksgiving_music_stop:
    loop_Sabres1:
      action: stop
      
  mode_door_thanksgiving_stopping:
    loop_Sabres1:
      action: stop
      

  thanksgiving_soup_score_increased: jackpot
  thanksgiving_soup_value_increased: 'yes'


widget_player:
  show_thanks_msg_1: 
    thanks_jackpot_value:
      widget_settings:    
        expire: 1.95s
      slide: leftframe                        
  show_thanks_msg_2: 
    thanks_increase_jackpot:
      widget_settings:    
        expire: 1.95s
      slide: leftframe                        
  show_thanks_msg_3: 
    thanks_shoot_soup:
      widget_settings:    
        expire: 1.95s
      slide: leftframe    

  show_thanks_msg_1_n: 
    thanks_jackpot_value_n:
      widget_settings:    
        expire: 1.95s
      slide: leftframe
  show_thanks_msg_2_n: 
    thanks_increase_jackpot_n:
      widget_settings:    
        expire: 1.95s
      slide: leftframe        
  show_thanks_msg_3_n: 
    thanks_shoot_soup_n:
      widget_settings:    
        expire: 1.95s
      slide: leftframe      
      
  show_thanks_slide_wide:
    widget_thanks_wide: 
      slide: leftframe     
      
  show_thanks_slide_narrow:   
    widget_thanks_narrow:  
      slide: leftframe     

  show_thanks_slide_full:
    widget_thanks_full: 
      widget_settings:    
        expire: 5s
      slide: leftframe      

  remove_thanks_slide_wide:
    widget_thanks_wide:     
      action: remove
      slide: leftframe
  
  remove_thanks_slide_narrow:
    widget_thanks_narrow:  
      action: remove     
      slide: leftframe

  remove_thanks_slide_full:
    widget_thanks_full:  
      action: remove     
      slide: leftframe
      
  remove_thanks_messages:      
    thanks_jackpot_value:
      action: remove    
      slide: leftframe     
    thanks_increase_jackpot:
      action: remove    
      slide: leftframe     
    thanks_shoot_soup:
      action: remove    
      slide: leftframe     
    thanks_jackpot_value_n:
      action: remove    
      slide: leftframe     
    thanks_increase_jackpot_n:
      action: remove    
      slide: leftframe     
    thanks_shoot_soup_n:
      action: remove
      slide: leftframe     
      
      


widgets:
  thanks_jackpot_value:
      - type: text
        style: tall_title
        font_size: 16
        text: Jackpot at (door_thanksgiving_soup_value)
        number_grouping: true        
        y: 90
        z: -110
  thanks_increase_jackpot:
      - type: text
        style: tall_title
        font_size: 16
        text: WHITE LOOPS INCREASE JACKPOT
        y: 90
        z: -110
  thanks_shoot_soup:
      - type: text
        style: tall_title
        font_size: 16
        text: SHOOT SOUP TO COLLECT
        y: 90
        z: -110

  thanks_jackpot_value_n:
      - type: text
        style: tall_title
        font_size: 14
        text: Jackpot at 
        x: 52
        y: 105
        z: -110
      - type: text
        style: tall_title
        font_size: 14
        text: (door_thanksgiving_soup_value)
        number_grouping: true                
        x: 52
        y: 90
        z: -110

  thanks_increase_jackpot_n:
      - type: text
        style: tall_title
        font_size: 14
        text: WHITE LOOPS 
        x: 52        
        y: 105
        z: -110
      - type: text
        style: tall_title
        font_size: 14
        text: INCREASE JACKPOT
        x: 52        
        y: 90
        z: -110
        
  thanks_shoot_soup_n:
      - type: text
        style: tall_title
        font_size: 14
        text: SHOOT SOUP
        x: 52        
        y: 105
        z: -110
      - type: text
        style: tall_title
        font_size: 14
        text: TO COLLECT
        x: 52        
        y: 90
        z: -110
        
  widget_thanks_narrow:
      - type: text
        style: tall_title
        font_size: 16
        text: THANKSGIVING
        color: ffff80
        anchor_y: top
        y: top
        x: 52
        z: -101
      - type: text
        text: (door_thanksgiving_soup_score)
        number_grouping: true
        min_digits: 2
        style: tall_title
        font_size: 13
        color: ffff80
        x: 52        
        y: 71
        z: -102        
      - type: text
        text: (door_thanksgiving_soup_score)
        number_grouping: true
        min_digits: 2
        style: tall_title
        font_size: 13
        color: 000000
        x: 53
        y: 70
        z: -101        
      - type: text
        style: tall_title
        font_size: 16
        text: (door_thanksgiving_timeleft)
        y: 8
        x: 95        
        z: -3000
      - type: image
        image: thanksgiving_door_2
        anchor_y: top
        anchor_x: left
        y: top
        x: 0
        z: -100 

        

  widget_thanks_wide:
      - type: text
        style: tall_title
        font_size: 32
        text: THANKSGIVING
        color: ffff80
        anchor_y: top
        y: top
        x: 105        
        z: -101 
      - type: text
        text: (door_thanksgiving_soup_score)
        number_grouping: true
        min_digits: 2
        style: tall_title
        font_size: 26
        color: ffff80
        x: 105
        y: 71
        z: -102        
      - type: text
        text: (door_thanksgiving_soup_score)
        number_grouping: true
        min_digits: 2
        style: tall_title
        font_size: 26
        color: 000000
        x: 106
        y: 70
        z: -101         
      - type: text
        style: tall_title
        font_size: 16
        text: (door_thanksgiving_timeleft)
        x: 105        
        y: 8
        z: -3000        
      - type: image
        image: thanksgiving_door
        anchor_y: top
        anchor_x: left
        y: top
        x: 0        
        z: -100        
        

  widget_thanks_full:
      - type: text
        style: tall_title
        font_size: 32
        text: THANKSGIVING INTRO
        color: ffff80
        anchor_y: top
        y: 128
        x: 105        
        z: -101
      - type: text
        text: 5 second vid
        style: tall_title
        font_size: 26
        color: white
        x: 105
        y: 71
        z: -101        
      - type: image
        image: thanksgiving_door
        anchor_y: top
        anchor_x: left
        y: 128
        x: 0        
        z: -100        
