# config_version=4
# NBX (The Nightmare Before Christmas Pinball)

#VM_This_Is_Halloween

mode:
  start_events: player_turn_start
  stop_events: game_ending
  code: VM_This_Is_Halloween.VM_This_Is_Halloween
  priority: 800

