#config_version=4
# NBX (The Nightmare Before Christmas Pinball)

tilt:
  tilt_warning_switch_tag: tilt_warning
#    tilt_switch_tag: tilt_warning
  slam_tilt_switch_tag: slam_sw
  warnings_to_tilt: 3
  reset_warnings_events: ball_ended
  multiple_hit_window: 200ms
  settle_time: 5s
  tilt_warnings_player_var: tilt_warnings


sound_player:
  tilt_warning_1: distbd1
  tilt_warning_2: distbd1
  tilt_1: ha_ha_huh_huh
  tilt_2: ha_ha_haha_haha

random_event_player:
  tilt:
  - tilt_1
  - tilt_2


     
widget_player:
  tilt_warning_1: 
    w_tilt_warning_1:
      widget_settings:    
        expire: 2s
      slide: leftframe        
      
  tilt_warning_2: 
    w_tilt_warning_2:
      widget_settings:    
        expire: 3s
      slide: leftframe        
    w_tilt_warning_1:      
      action: remove
      
  tilt: 
    w_tilt:
      slide: leftframe        
    w_tilt_warning_2:      
      action: remove
    
  ball_ended: 
    w_tilt:
      action: remove
    

widgets:
  w_tilt_warning_1:
  - type: text
    style: tall_title
    font_size: 32
    text: HEY!
    color: ffff00
    y: 20
    z: -4301
  - type: image
    image: scary_jack
    anchor_y: top
    anchor_x: left
    y: top
    x: 0        
    z: -4300        

  w_tilt_warning_2:
  - type: text
    style: tall_title
    font_size: 32
    text: WHATCH IT!
    color: ffff00
    y: 20
    z: -4301
  - type: image
    image: scary_jack
    anchor_y: top
    anchor_x: left
    y: top
    x: 0        
    z: -4300        

  w_tilt:
  - type: text
    style: tall_title
    font_size: 32
    text: TILT
    color: ffff00
    y: 20
    x: 105
    z: -4302
  - type: video
    video: redjack
    z: -4300        
 
    

    
