# config_version=4
# NBX (The Nightmare Before Christmas Pinball)

#Oogie mode 6 

mode:
  start_events: ob_mode_6_start
  stop_events: ob_mode_6_stop
  code: OB_Unravel.OB_Unravel
  priority: 800

  
sound_player:
  OB_Unravel_music_start:
    loop_This_is_halloween_finale:
      action: play    
      loops: -1
      volume: 0.5 

  OB_Unravel_music_stop:
    loop_This_is_halloween_finale:
      action: stop

  mode_OB_Unravel_stopping:
    loop_This_is_halloween_finale:
      action: stop


widget_player:
  show_OB_Unravel_slide_wide:
    widget_OBUNRAVEL_wide: 
      slide: leftframe     
      
  show_OB_Unravel_slide_narrow:   
    widget_OBUNRAVEL_narrow:  
      slide: leftframe

  show_OB_Unravel_slide_intro:
    widget_OBUNRAVEL_full:   
      slide: leftframe  
      widget_settings:    
        expire: 5s      
      
  show_OB_Unravel_msg_1:         
    widget_OB_Unravel_msg_1:    
      slide: leftframe  
      widget_settings:    
        expire: 1.95s      

  show_OB_Unravel_msg_1_n:         
    widget_OB_Unravel_msg_1_n:    
      slide: leftframe    
      widget_settings:    
        expire: 1.95s      

  show_OB_Unravel_msg_2:         
    widget_OB_Unravel_msg_2:    
      slide: leftframe  
      widget_settings:    
        expire: 1.95s      

  show_OB_Unravel_msg_2_n:         
    widget_OB_Unravel_msg_2_n:    
      slide: leftframe    
      widget_settings:    
        expire: 1.95s      


  remove_OB_Unravel_slide_wide:
    widget_OBUNRAVEL_wide: 
      action: remove
      slide: leftframe      
    
  remove_OB_Unravel_slide_narrow:      
    widget_OBUNRAVEL_narrow:    
      action: remove
      slide: leftframe      
                  
  remove_OB_Unravel_slide_intro:      
    widget_OBUNRAVEL_full:    
      action: remove
      slide: leftframe      

  remove_OB_Unravel_messages:
    widget_OB_Unravel_msg_1:    
      action: remove  
      slide: leftframe
    widget_OB_Unravel_msg_1_n:        
      action: remove
      slide: leftframe      
    widget_OB_Unravel_msg_2:    
      action: remove
      slide: leftframe
    widget_OB_Unravel_msg_2_n:        
      action: remove
      slide: leftframe
      
    
    

widgets:      
  widget_OB_Unravel_msg_1:
      - type: text
        style: tall_title
        font_size: 26
        text: Distract OOGIE!
        y: 90
        z: -110        

  widget_OB_Unravel_msg_2:
      - type: text
        style: tall_title
        font_size: 26
        text: SOUP and SPINNER
        y: 90
        z: -110        
        
  widget_OB_Unravel_msg_1_n:
      - type: text
        style: tall_title
        font_size: 16
        text: Distract OOGIE
        y: 90
        x: 157
        z: -110        

  widget_OB_Unravel_msg_2_n:
      - type: text
        style: tall_title
        font_size: 16
        text: SOUP and SPINNER
        y: 95
        x: 157
        z: -110        


  widget_OBUNRAVEL_narrow:
      - type: text
        style: tall_title
        font_size: 16
        text: UNRAVEL OOGIE
        color: ff33ff
        anchor_y: top
        y: 128
        x: 157
        z: -102
      - type: text
        style: tall_title
        font_size: 16
        text: UNRAVEL OOGIE
        color: black
        anchor_y: top
        y: 127
        x: 158
        z: -101
      - type: text
        style: tall_title
        font_size: 16
        text: (OB_Unravel_timeleft)
        y: 8
        x: 115  
        z: -3000      
      - type: image
        image: unravel_backdrop_2
        anchor_y: top
        anchor_x: left
        y: top
        x: 105
        z: -100        

  widget_OBUNRAVEL_wide:
      - type: text
        style: tall_title
        font_size: 32
        text: UNRAVEL OOGIE
        color: ff33ff
        anchor_y: top
        y: 128
        x: 105        
        z: -102
      - type: text
        style: tall_title
        font_size: 32
        text: UNRAVEL OOGIE
        color: black
        anchor_y: top
        y: 127
        x: 106        
        z: -101
      - type: text
        style: tall_title
        font_size: 16
        text: (OB_Unravel_timeleft)
        y: 8
        x: 105   
        z: -3000     
      - type: image
        image: unravel_backdrop
        anchor_y: top
        anchor_x: left
        y: top
        x: 0        
        z: -100        
               
  widget_OBUNRAVEL_full:
      - type: text
        style: tall_title
        font_size: 32
        text: UNRAVEL OOGIE INTRO
        color: purple
        anchor_y: top
        y: 128
        x: 105        
        z: -102
      - type: text
        style: tall_title
        font_size: 32
        text: OB VS UNRAVEL INTRO
        color: black
        anchor_y: top
        y: 127
        x: 106        
        z: -101
      - type: text
        style: tall_title
        font_size: 24
        text: 5 second vid
        color: white
        anchor_y: top
        y: 100
        x: 105        
        z: -101
      - type: image
        image: unravel_backdrop
        anchor_y: top
        anchor_x: left
        y: top
        x: 0        
        z: -100        


